//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hviktor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hviktor.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta meg til sikkerhet.
        /// </summary>
        public static string Blazor_Modal_Error_BackToSafety {
            get {
                return ResourceManager.GetString("Blazor.Modal.Error.BackToSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lukk.
        /// </summary>
        public static string Blazor_Modal_Error_Close {
            get {
                return ResourceManager.GetString("Blazor.Modal.Error.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last siden på nytt eller gå til sikkerhet..
        /// </summary>
        public static string Blazor_Modal_Error_Description {
            get {
                return ResourceManager.GetString("Blazor.Modal.Error.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last inn siden på nytt.
        /// </summary>
        public static string Blazor_Modal_Error_Reload {
            get {
                return ResourceManager.GetString("Blazor.Modal.Error.Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det har oppstått en uhåndtert feil..
        /// </summary>
        public static string Blazor_Modal_Error_Title {
            get {
                return ResourceManager.GetString("Blazor.Modal.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke koble til serveren....
        /// </summary>
        public static string Blazor_Modal_Reconnect_Failed {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prøv igjen.
        /// </summary>
        public static string Blazor_Modal_Reconnect_Failed_TryAgain {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.Failed.TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kobler til serveren på nytt....
        /// </summary>
        public static string Blazor_Modal_Reconnect_FirstAttempt {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.FirstAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilkoblingsstatus.
        /// </summary>
        public static string Blazor_Modal_Reconnect_Heading {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Økten har blitt pauset av serveren..
        /// </summary>
        public static string Blazor_Modal_Reconnect_Paused {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjenoppta.
        /// </summary>
        public static string Blazor_Modal_Reconnect_Paused_Resume {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.Paused.Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har blitt kastet ut fra serveren..
        /// </summary>
        public static string Blazor_Modal_Reconnect_Rejected {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilkobling mislyktes... prøver igjen om {0} sekunder..
        /// </summary>
        public static string Blazor_Modal_Reconnect_RepeatedAttempt {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.RepeatedAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunne ikke fortsette økten..
        /// </summary>
        public static string Blazor_Modal_Reconnect_ResumeFailed {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.ResumeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last inn siden på nytt.
        /// </summary>
        public static string Blazor_Modal_Reconnect_ResumeFailed_Reload {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.ResumeFailed.Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilkobling til serveren gjenopprettet..
        /// </summary>
        public static string Blazor_Modal_Reconnect_Success {
            get {
                return ResourceManager.GetString("Blazor.Modal.Reconnect.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vennligst se IDEen for mer informasjon..
        /// </summary>
        public static string DotNet_Modal_Error_Description {
            get {
                return ResourceManager.GetString("DotNet.Modal.Error.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En feil oppstod under hot-reload prosjektbygging..
        /// </summary>
        public static string DotNet_Modal_Error_Title {
            get {
                return ResourceManager.GetString("DotNet.Modal.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier kodeblokk.
        /// </summary>
        public static string Hviktor_Components_CodeBlock_AriaLabel {
            get {
                return ResourceManager.GetString("Hviktor.Components.CodeBlock.AriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiert.
        /// </summary>
        public static string Hviktor_Components_CodeBlock_Copied_Button {
            get {
                return ResourceManager.GetString("Hviktor.Components.CodeBlock.Copied.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kode kopiert til utklippstavle.
        /// </summary>
        public static string Hviktor_Components_CodeBlock_CopiedAnnouncement {
            get {
                return ResourceManager.GetString("Hviktor.Components.CodeBlock.CopiedAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier.
        /// </summary>
        public static string Hviktor_Components_CodeBlock_Copy_Button {
            get {
                return ResourceManager.GetString("Hviktor.Components.CodeBlock.Copy.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lukk dialogvindu.
        /// </summary>
        public static string Hviktor_Components_Dialog_Button_Close {
            get {
                return ResourceManager.GetString("Hviktor.Components.Dialog.Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last inn siden på nytt.
        /// </summary>
        public static string Hviktor_Components_Loader_Loader_Button_Refresh {
            get {
                return ResourceManager.GetString("Hviktor.Components.Loader.Loader.Button.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paginering.
        /// </summary>
        public static string Hviktor_Components_Pagination_AriaLabel {
            get {
                return ResourceManager.GetString("Hviktor.Components.Pagination.AriaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tøm valg.
        /// </summary>
        public static string Hviktor_Components_Suggestion_Clear {
            get {
                return ResourceManager.GetString("Hviktor.Components.Suggestion.Clear", resourceCulture);
            }
        }
    }
}
