//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Documentation.Resources.DocumentationResources", typeof(DocumentationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er et farevarsel..
        /// </summary>
        public static string Alert_Danger {
            get {
                return ResourceManager.GetString("Alert_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er et standard informasjonsvarsel..
        /// </summary>
        public static string Alert_DefaultInfo {
            get {
                return ResourceManager.GetString("Alert_DefaultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er et suksessvarsel..
        /// </summary>
        public static string Alert_Success {
            get {
                return ResourceManager.GetString("Alert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er et advarselsvarsel..
        /// </summary>
        public static string Alert_Warning {
            get {
                return ResourceManager.GetString("Alert_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avkrysset.
        /// </summary>
        public static string Checkbox_Checked {
            get {
                return ResourceManager.GetString("Checkbox_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrollert avkrysningsboks.
        /// </summary>
        public static string Checkbox_ControlledLabel {
            get {
                return ResourceManager.GetString("Checkbox_ControlledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard avkrysningsboks.
        /// </summary>
        public static string Checkbox_DefaultLabel {
            get {
                return ResourceManager.GetString("Checkbox_DefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne avkrysningsboksen er deaktivert og avkrysset.
        /// </summary>
        public static string Checkbox_DisabledCheckedDescription {
            get {
                return ResourceManager.GetString("Checkbox_DisabledCheckedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivert (avkrysset).
        /// </summary>
        public static string Checkbox_DisabledCheckedLabel {
            get {
                return ResourceManager.GetString("Checkbox_DisabledCheckedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne avkrysningsboksen er deaktivert og ikke avkrysset.
        /// </summary>
        public static string Checkbox_DisabledUncheckedDescription {
            get {
                return ResourceManager.GetString("Checkbox_DisabledUncheckedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivert (ikke avkrysset).
        /// </summary>
        public static string Checkbox_DisabledUncheckedLabel {
            get {
                return ResourceManager.GetString("Checkbox_DisabledUncheckedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubestemt avkrysningsboks (velg alle/noen/ingen).
        /// </summary>
        public static string Checkbox_IndeterminateTitle {
            get {
                return ResourceManager.GetString("Checkbox_IndeterminateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ 1.
        /// </summary>
        public static string Checkbox_Option1 {
            get {
                return ResourceManager.GetString("Checkbox_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ 2.
        /// </summary>
        public static string Checkbox_Option2 {
            get {
                return ResourceManager.GetString("Checkbox_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ 3.
        /// </summary>
        public static string Checkbox_Option3 {
            get {
                return ResourceManager.GetString("Checkbox_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne avkrysningsboksen er skrivebeskyttet og avkrysset.
        /// </summary>
        public static string Checkbox_ReadOnlyCheckedDescription {
            get {
                return ResourceManager.GetString("Checkbox_ReadOnlyCheckedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrivebeskyttet (avkrysset).
        /// </summary>
        public static string Checkbox_ReadOnlyCheckedLabel {
            get {
                return ResourceManager.GetString("Checkbox_ReadOnlyCheckedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne avkrysningsboksen er skrivebeskyttet og ikke avkrysset.
        /// </summary>
        public static string Checkbox_ReadOnlyUncheckedDescription {
            get {
                return ResourceManager.GetString("Checkbox_ReadOnlyUncheckedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrivebeskyttet (ikke avkrysset).
        /// </summary>
        public static string Checkbox_ReadOnlyUncheckedLabel {
            get {
                return ResourceManager.GetString("Checkbox_ReadOnlyUncheckedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg alle.
        /// </summary>
        public static string Checkbox_SelectAll {
            get {
                return ResourceManager.GetString("Checkbox_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive filtre:.
        /// </summary>
        public static string ChipRemovable_ActiveFilters {
            get {
                return ResourceManager.GetString("ChipRemovable_ActiveFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen aktive filtre.
        /// </summary>
        public static string ChipRemovable_NoFilters {
            get {
                return ResourceManager.GetString("ChipRemovable_NoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilbakestill.
        /// </summary>
        public static string ChipRemovable_Reset {
            get {
                return ResourceManager.GetString("ChipRemovable_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etikett.
        /// </summary>
        public static string ChipRemovable_Tag {
            get {
                return ResourceManager.GetString("ChipRemovable_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekreft.
        /// </summary>
        public static string Dialog_Confirm {
            get {
                return ResourceManager.GetString("Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er en dialog. Klikk utenfor eller på lukkeknappen for å lukke..
        /// </summary>
        public static string Dialog_ExampleContent {
            get {
                return ResourceManager.GetString("Dialog_ExampleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogtittel.
        /// </summary>
        public static string Dialog_ExampleTitle {
            get {
                return ResourceManager.GetString("Dialog_ExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åpne dialog.
        /// </summary>
        public static string Dialog_OpenButton {
            get {
                return ResourceManager.GetString("Dialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling.
        /// </summary>
        public static string Dropdown_Action {
            get {
                return ResourceManager.GetString("Dropdown_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lukk meg.
        /// </summary>
        public static string Dropdown_CloseMe {
            get {
                return ResourceManager.GetString("Dropdown_CloseMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avdeling.
        /// </summary>
        public static string Dropdown_Column_Department {
            get {
                return ResourceManager.GetString("Dropdown_Column_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string Dropdown_Column_Email {
            get {
                return ResourceManager.GetString("Dropdown_Column_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        public static string Dropdown_Column_Name {
            get {
                return ResourceManager.GetString("Dropdown_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string Dropdown_Column_Role {
            get {
                return ResourceManager.GetString("Dropdown_Column_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Dropdown_Column_Status {
            get {
                return ResourceManager.GetString("Dropdown_Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg kolonner.
        /// </summary>
        public static string Dropdown_Columns {
            get {
                return ResourceManager.GetString("Dropdown_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} av {1} valgt.
        /// </summary>
        public static string Dropdown_ColumnsSelected {
            get {
                return ResourceManager.GetString("Dropdown_ColumnsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrollert.
        /// </summary>
        public static string Dropdown_Controlled {
            get {
                return ResourceManager.GetString("Dropdown_Controlled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åpne nedtrekksmeny.
        /// </summary>
        public static string Dropdown_OpenButton {
            get {
                return ResourceManager.GetString("Dropdown_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato og tid.
        /// </summary>
        public static string Input_DateTimeTitle {
            get {
                return ResourceManager.GetString("Input_DateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Input_Default {
            get {
                return ResourceManager.GetString("Input_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv her....
        /// </summary>
        public static string Input_DefaultPlaceholder {
            get {
                return ResourceManager.GetString("Input_DefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivert.
        /// </summary>
        public static string Input_Disabled {
            get {
                return ResourceManager.GetString("Input_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke tilgjengelig.
        /// </summary>
        public static string Input_DisabledPlaceholder {
            get {
                return ResourceManager.GetString("Input_DisabledPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andre typer.
        /// </summary>
        public static string Input_OtherTypesTitle {
            get {
                return ResourceManager.GetString("Input_OtherTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrivebeskyttet.
        /// </summary>
        public static string Input_ReadOnly {
            get {
                return ResourceManager.GetString("Input_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne verdien kan ikke endres.
        /// </summary>
        public static string Input_ReadOnlyValue {
            get {
                return ResourceManager.GetString("Input_ReadOnlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle (ARIA).
        /// </summary>
        public static string Input_RoleTitle {
            get {
                return ResourceManager.GetString("Input_RoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk....
        /// </summary>
        public static string Input_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Input_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilstander.
        /// </summary>
        public static string Input_StatesTitle {
            get {
                return ResourceManager.GetString("Input_StatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiver funksjon.
        /// </summary>
        public static string Input_SwitchLabel {
            get {
                return ResourceManager.GetString("Input_SwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputtyper.
        /// </summary>
        public static string Input_TypesTitle {
            get {
                return ResourceManager.GetString("Input_TypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne siden viser alle tilgjengelige komponenter i Hviktor-biblioteket med eksempler og kodeeksempler..
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hviktor komponentbibliotek.
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentasjon.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overskriftsnivå.
        /// </summary>
        public static string Typography_HeadingLevel {
            get {
                return ResourceManager.GetString("Typography_HeadingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er en etikett.
        /// </summary>
        public static string Typography_Label {
            get {
                return ResourceManager.GetString("Typography_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er et avsnitt med litt tekstinnhold..
        /// </summary>
        public static string Typography_Paragraph {
            get {
                return ResourceManager.GetString("Typography_Paragraph", resourceCulture);
            }
        }
    }
}
