name: Playwright WCAG tests

on:
  workflow_call:
    inputs:
      browser:
        description: 'Browser to use for tests'
        required: false
        default: 'chromium'
        type: string
      channel:
        description: 'Browser channel to use for tests'
        required: false
        default: ''
        type: string
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to use for tests'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
      channel:
        description: 'Browser channel to use for tests'
        required: false
        default: ''
        type: choice
        options:
          - ''
          - msedge
          - chrome

concurrency:
  group: playwright-wcag-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prerequisite:
    name: Prerequisite tests
    uses: ./.github/workflows/playwright-reusable.yml
    with:
      test-name: Prerequisite
      test-filter: "Collection=Prerequisite"
      browser: ${{ inputs.browser }}
      channel: ${{ inputs.channel }}

  wcag-tests:
    name: WCAG All Levels (A + AA + AAA + Best Practices)
    needs: [ prerequisite ]
    uses: ./.github/workflows/playwright-reusable.yml
    with:
      test-name: WCAG All Levels
      test-filter: "Tags=wcag"
      browser: ${{ inputs.browser }}
      channel: ${{ inputs.channel }}
